# Generated by Django 2.2.4 on 2021-03-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField(max_length=8)),
                ('email', models.EmailField(blank=True, max_length=100)),
            ],
        ),
    ]
